# Sample .travis.yml for R projects.
#
# Using standard travis R build env now
# from here: https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r_github_packages: GLEON/GLMr

r:
  - oldrel
  - release
  - devel

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --as-cran
  
after_success:
  - Rscript -e 'covr::coveralls()'
